---
title: "Aleksander Bang-Larsen's CV"
author: Aleksander Bang-Larsen
date: "`r Sys.Date()`"
params:
  pdf_mode:
    value: true
output:
  pagedown::html_resume:
    css: ['dd_cv.css', 'resume']
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results='asis',
  echo = FALSE
)

library(magrittr) # For the pipe
source("cv_printing_functions.r")

# Read in all data and initialize a CV printer object
CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1c23M18bAcy3k8gQCXM2dDgo_5yP50fYWrKidRnjQa2Y/edit?usp=sharing",
  pdf_mode = params$pdf_mode
)

```


```{r}
# When in pdf export mode the little dots are unaligned, so fix that with some conditional CSS.
if(params$pdf_mode) {
    cat("
<style>
:root{
  --decorator-outer-offset-left: -6.5px;
}
</style>")
}
```


Aside
================================================================================

```{r}
# Build interactive network of positions colored by section
# and connected if they occurred in the same year
datadrivencv::build_network_logo(CV$entries_data)
```


```{r}
if(params$pdf_mode){
  cat("Find dette CV online på _cv.aleksanderbl.dk_")
} else {
  cat("[<i class='fas fa-download'></i> Hent en PDF af dette CV](https://github.com/aleksanderbl29/cv-from-r/raw/main/bang-larsen_cv.pdf)")
}
```

Kontakt {#kontakt}
--------------------------------------------------------------------------------

```{r}
CV %>% print_kontakt_info()
```



Kompetencer {#skills}
--------------------------------------------------------------------------------

```{r}
CV %>% print_skill_bars()
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Lavet med R-pakken [**pagedown**](https://github.com/rstudio/pagedown).

Kildekoden kan findes på [github.com/aleksanderbl29/cv-from-r](https://github.com/aleksanderbl29/cv-from-r).

Sidst opdateret `r Sys.Date()`.



Main
================================================================================

Aleksander Bang-Larsen {#title}
--------------------------------------------------------------------------------

```{r}
# Note the special double pipe so we modify the CV object in place
CV %<>% print_text_block("intro")
```


Uddannelse {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
CV %<>% print_section('uddannelse')
```


Erfaring {data-icon=suitcase}
--------------------------------------------------------------------------------


```{r}
CV %<>% print_section('erfaring')
```
